stages:  
  - build
  - clean
 
install-dep:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    GITHUB_ACTIONS: 1
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  script:
    - git submodule update --init --recursive
    - echo test
    - cd RobustToolbox
    - git submodule update --init --recursive

build:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    GITHUB_ACTIONS: 1
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  script:
    - /home/gitlab-runner/.dotnet/dotnet restore
    - /home/gitlab-runner/.dotnet/dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
    - /home/gitlab-runner/.dotnet/dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
    - echo "Compile complete."

remove-build:
  stage: clean
  when: on_failure
  script:
    - cd ..
    - rm -R space_station