stages:  
  - build
  - clean
 
install-dep:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    GITHUB_ACTIONS: 1
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  artifacts:
    paths: 
      - ./
  script:
    - |
      git submodule update --init --recursive
      cd RobustToolbox
      git submodule update --init --recursive

build:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    GITHUB_ACTIONS: 1
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  script:
    - |
      dotnet restore
      dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
      echo "Compile complete."

remove-build:
  stage: clean
  when: on_failure
  script:
    - cd ..
    - rm -R space_station