- type: startingGear
  id: ERTSecurityGearEVA_L
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlue
    back: ClothingBackpackERTSecurityFilledL
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitStorage: OxygenTankFilled
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltMilitaryWebbingL
    pocket1: