- type: job
  id: ADTBrigMedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobADTBrigMedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000     
  weight: 20
  startingGear: ADTBrigMedic
  icon: "ADTBrigMedic"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Service
  - External
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
- type: startingGear
  id: ADTBrigMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    outerClothing: ADTClothingOuterCoatLabSec
    id: ADTBrigMedicPDA
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetADTBrigMedic
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled

- type: entity
  id: SpawnADTBrigMedic
  parent: SpawnPointJobBase
  name: brig medic spawn
  components:
    - type: SpawnPoint
      job_id: ADTBrigMedic
    - type: Sprite
      layers:
        - state: green
        - state: hop

- type: entity
  parent: BasePDA
  id: ADTBrigMedicPDA
  name: brig medic PDA
  description: brig medic PDA
  components:
  - type: PDA
    id: ADTBrigMedicIDCard
    state: pda-medical
  - type: PDABorderColor
    borderColor: "#d7d7d0"
    accentVColor: "#447987"
  - type: Icon
    state: pda-medical
  - type: HealthAnalyzer
    scanDelay: 1
    scanningEndSound:
      path: "/Audio/Items/Medical/healthscanner.ogg"



- type: entity
  parent: IDCardStandard
  id: ADTBrigMedicIDCard
  name: Brig Medic ID card
  components:
  - type: Sprite
    layers:
    - state: default
    - state: idpsychologist
  - type: PresetIdCard
    job: ADTBrigMedic
